=== matthiaw/js-ref/src/data/reference.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "https://github.com/matthiaw/js-ref/blob/master/src/data/reference.schema.json",
  "type": "object",
  "properties": {
    "package": {
      "$id": "/properties/package",
      "type": "string",
      "title": "The Package-Name of the JavaScript-Element.",
      "description": "The package explains which JavaScript-Library contains the described element. This should be always correspond to the npm-repository with library-name and version, like package@version.",
      "default": "",
      "examples": [
        "react@16.2.0"
      ]
    },
    "name": {
      "$id": "/properties/name",
      "type": "string",
      "title": "The Name of the Element.",
      "description": "The name which defines the element.",
      "default": "",
      "examples": [
        "Children"
      ]
    },
    "_name_comment": {
      "$id": "/properties/_name_comment",
      "type": "string",
      "title": "Comment for the name of the component.",
      "description": "Explanation to the name of the component. Is used as tooltip.",
      "default": "",
      "examples": [
        ""
      ]
    },
    "description": {
      "$id": "/properties/description",
      "type": "string",
      "title": "Text which describes the usage of the JavaScript Element.",
      "description": "In human readable sentences, the usage of the element should be described. Html-Code could be used.",
      "default": "",
      "examples": [
        "<code>React.Children</code> provides utilities for dealing with the <code>this.props.children</code> opaque data structure."
      ]
    },
    "datatype": {
      "$id": "/properties/datatype",
      "type": "string",
      "title": "Datatype of the element",
      "description": "Datatype of the element. Could be Condition, Function, Class, Object, ...",
      "default": "",
      "examples": [
        "function"
      ]
    },
    "_datatype_comment": {
      "$id": "/properties/_datatype_comment",
      "type": "string",
      "title": "Comment to the datatype.",
      "description": "Comment of the datatype. Is used as tooltip over the datatype.",
      "default": "",
      "examples": [
        "Found with typeof Component"
      ]
    },
    "childof": {
      "$id": "/properties/childof",
      "type": "string",
      "title": "Name of the parent",
      "description": "Parent-Element of the named element. Could be empty.",
      "default": "",
      "examples": [
        "React"
      ]
    },
    "_childof_comment": {
      "$id": "/properties/_childof_comment",
      "type": "string",
      "title": "Comment to the parent",
      "description": "Comment to the parent. Used as tooltip.",
      "default": "",
      "examples": [
        ""
      ]
    },
    "code": {
      "$id": "/properties/code",
      "type": "string",
      "title": "Code Statement as example for the element",
      "description": "Code which exlains the usage of the element.",
      "default": "",
      "examples": [
        "React.Children.map(children, function[(thisArg)])"
      ]
    },
    "note": {
      "$id": "/properties/note",
      "type": "string",
      "title": "Note to the element",
      "description": "Explains rules, principals and necessary notes which should be recognized by using the element.",
      "default": "",
      "examples": [
        "-"
      ]
    },
    "parameters": {
      "$id": "/properties/parameters",
      "type": "array",
      "items": {
        "$id": "/properties/parameters/items",
        "type": "object",
        "properties": {
          "name": {
            "$id": "/properties/parameters/items/properties/name",
            "type": "string",
            "title": "Property-Name of the Element",
            "description": "Properties are variables, boolean flags or default values. Functional element should be declared under method section.",
            "default": "",
            "examples": [
              "none"
            ]
          },
          "description": {
            "$id": "/properties/parameters/items/properties/description",
            "type": "string",
            "title": "Description of the Property",
            "description": "Description of the property, which explains the purpose of the property.",
            "default": "",
            "examples": [
              ""
            ]
          },
          "note": {
            "$id": "/properties/parameters/items/properties/note",
            "type": "string",
            "title": "Note for the property",
            "description": "Rule or principle which is important to use the property.",
            "default": "",
            "examples": [
              ""
            ]
          },
          "code_example": {
            "$id": "/properties/parameters/items/properties/code_example",
            "type": "string",
            "title": "Code example for the usage of the property",
            "description": "A code snippet which explains the usage of the property.",
            "default": "",
            "examples": [
              "var hi = \"Hello World!\n42 is still meaningfull.\""
            ]
          }
        }
      }
    },
    "methods": {
      "$id": "/properties/methods",
      "type": "array",
      "items": {
        "$id": "/properties/methods/items",
        "type": "object",
        "properties": {
          "name": {
            "$id": "/properties/methods/items/properties/name",
            "type": "string",
            "title": "Name of the method",
            "description": "Name which calls the method.",
            "default": "",
            "examples": [
              "map"
            ]
          },
          "statement": {
            "$id": "/properties/methods/items/properties/statement",
            "type": "string",
            "title": "Code statement of the method",
            "description": "Code-line which shows what calls the methods (including all parameters)",
            "default": "",
            "examples": [
              "map(children, function[(thisArg)])"
            ]
          },
          "code_example": {
            "$id": "/properties/methods/items/properties/code_example",
            "type": "string",
            "title": "Code example of the method",
            "description": "Code-Example of the method",
            "default": "",
            "examples": [
              ""
            ]
          },
          "description": {
            "$id": "/properties/methods/items/properties/description",
            "type": "string",
            "title": "Description of the method.",
            "description": "Text which eplains the reason for the method.",
            "default": "",
            "examples": [
              "Invokes a function on every immediate child contained within <code>children</code> with this set to <code>thisArg</code>. If <code>children</code> is a keyed fragment or array it will be traversed: the function will never be passed the container objects. If children is <code>null</code> or <code>undefined</code>, returns <code>null</code> or <code>undefined</code> rather than an array."
            ]
          },
          "status": {
            "$id": "/properties/methods/items/properties/status",
            "type": "string",
            "title": "Status of the method.",
            "description": "Because JavaScript is not Java there is no type-safe validator which methods are needed, like a class-constructor or a mandatory method. For that the status can be required or optional.",
            "default": "optional",
            "examples": [
              "optional"
            ]
          },
          "returns": {
            "$id": "/properties/methods/items/properties/returns",
            "type": "string",
            "title": "Return value of the method.",
            "description": "Object, function, class or value which is returned by the method.",
            "default": "",
            "examples": [
              "[elements]"
            ]
          },
          "returns_description": {
            "$id": "/properties/methods/items/properties/returns_description",
            "type": "string",
            "title": "Description of the return statement.",
            "description": "Text which describes what with which purpose the method returns.",
            "default": "",
            "examples": [
              "Array of elements"
            ]
          },
          "parameters": {
            "$id": "/properties/methods/items/properties/parameters",
            "type": "array",
            "items": {
              "$id": "/properties/methods/items/properties/parameters/items",
              "type": "object",
              "properties": {
                "name": {
                  "$id": "/properties/methods/items/properties/parameters/items/properties/name",
                  "type": "string",
                  "title": "Property of the method",
                  "description": "Name of the property which should be set in the method header.",
                  "default": "",
                  "examples": [
                    "children"
                  ]
                },
                "description": {
                  "$id": "/properties/methods/items/properties/parameters/items/properties/description",
                  "type": "string",
                  "title": "The Description Schema.",
                  "description": "An explanation about the purpose of this instance.",
                  "default": "",
                  "examples": [
                    "Children which should be invoked with the given function"
                  ]
                },
                "note": {
                  "$id": "/properties/methods/items/properties/parameters/items/properties/note",
                  "type": "string",
                  "title": "Note of the property",
                  "description": "Note or Principal which describes what is importend when the property is set to the method.",
                  "default": "",
                  "examples": [
                    ""
                  ]
                },
                "code_example": {
                  "$id": "/properties/methods/items/properties/parameters/items/properties/code_example",
                  "type": "string",
                  "title": "Code Example of the property.",
                  "description": "Detailed code example which describes the usage of the property.",
                  "default": "",
                  "examples": [
                    ""
                  ]
                }
              }
            }
          }
        }
      }
    }
  }
}

=== matthiaw/js-ref/src/data/react.reference.json
{
	"package": "react@16.2.0",
	"name": "React",
	"datatype": "function",
	"_datatype_comment": "Found with typeof Component",
	"code": "import React from 'react';",
	"note": "React is the entry point to the React library. If you load React from a &lt;script&gt; tag, these top-level APIs are available on the React global. If you use <a href=\"http://es6-features.org/\">ES6</a> with npm, you can write <code>import React from 'react'</code>. If you use ES5 with npm, you can write <code>var React = require('react')</code>.",
	"parameters": [
		{
			"name": "none"
		}
	],
	"methods": [
		{
			"name": "createFactory",
			"statement": "createFactory(type)",
			"description": "Return a function that produces React elements of a given type. Like <code>React.createElement()</code>, the type argument can be either a tag name string (such as <code>'div'</code> or <code>'span'</code>), a React component type (a class or a function), or a React fragment type. This helper is considered legacy, and we encourage you to either use JSX or use <code>React.createElement()</code> directly instead. You will not typically invoke <code>React.createFactory()</code> directly if you are using JSX.",
			"status": "optional",
			"parameters": [
				{
					"name": "type",
					"description": "The type argument is either a string (HTML tag) or a class. It’s a description of what tag/class is going to be rendered and what props it will contain. You can also create factory functions for specific types.",
					"code_example": "var div = React.createFactory('div');var reactDivElement = div(props, children);"
				}
			]
		},
		{
			"name": "createElement",
			"statement": "createElement(component, props, ...children)",
			"code_example": "// the DOM-Elementconst element = <div class=\"hi\" id=\"greet\">Hello world!</div>;// is created withconst element = React.createElement(\"div\", { \"class\": \"hi\", id: \"greet\" }, \"Hello world!\");",
			"description": "Create and return a new React element of the given type. The type argument can be either a tag name string (such as <code>'div'</code> or <code>'span'</code>), a React component type (a class or a function), or a React fragment type.",
			"status": "optional",
			"parameters": [
				{
					"name": "type",
					"description": "Type of DOM which is used in the tag"
				},
				{
					"name": "props",
					"description": "Attributes of the DOM-Element"
				},
				{
					"name": "children",
					"description": "Content between the Start- ans Closing-Tag"
				}
			],
			"note": "Code written with JSX will be converted to use <code>React.createElement()</code>. You will not typically invoke <code>React.createElement()</code> directly if you are using JSX. For examples see <a href=\"https://babeljs.io/repl/#?presets=react&code_lz=GYVwdgxgLglg9mABACwKYBt1wBQEpEDeAUIogE6pQhlIA8AJjAG4B8AEhlogO5xnr0AhLQD0jVgG4iAXyJA\">JSX-to-JavaScript-Converter</a>."
		},
		{
			"name": "cloneElement",
			"statement": "React.cloneElement( element, [props], [...children] )",
			"description": "Clone and return a new React element using element as the starting point. The resulting element will have the original element’s props with the new props merged in shallowly. New children will replace existing children. <code>key</code> and <code>ref</code> from the original element will be preserved.",
			"status": "optional",
			"parameters": [
				{
					"name": "element",
					"description": "String of the DOM-Element which is cloned"
				},
				{
					"name": "props",
					"description": "Properties of the cloned DOM-Element"
				},
				{
					"name": "children",
					"description": "Children/Content between the Start- and End-Tag of the cloned Element."
				}
			]
		},
		{
			"name": "isValidElement",
			"statement": "isValidElement(object)",
			"description": "Verifies the object is a React element. Returns <code>true</code> or <code>false</code>.",
			"status": "optional",
			"parameters": [
				{
					"name": "object",
					"description": "Element which is verified."
				}
			]
		}
	]
}

=== matthiaw/js-ref/src/data/react.if.reference.json
{
	"package": "react@16.2.0",
	"name": "If-Else",
	"datatype": "conditional statement",
	"childof": "React",
	"code": "{ (this.props.value) ? <p>Hello World!</p> : null }",
	"note": "A conditional check with Standard-JavaScript If-Else-Clause inside React's JSX is not possible, because JSX is a shortended syntatic language. For more see <a href=\"https://react-cn.github.io/react/tips/if-else-in-JSX.html\">If-Else in JSX</a>.",
	"parameters": [
		{
			"name": "none"
		}
	],
	"methods": [
		{
			"name": "If-Else",
			"statement": "{condition ? 'true' : 'false'}",
			"status": "optional"
		}
	]
}

=== matthiaw/js-ref/src/data/react.children.reference.json
{
	"package": "react@16.2.0",
	"name": "Children",
	"description": "<code>React.Children</code> provides utilities for dealing with the <code>this.props.children</code> opaque data structure.",
	"datatype": "function",
	"_datatype_comment": "Found with typeof Component",
	"childof": "React",
	"code": "React.Children.map(children, function[(thisArg)])",
	"note": ".",
	"parameters": [
		{
			"name": "none",
			"description": ".",
			"note": "."
		}
	],
	"methods": [
		{
			"name": "map",
			"statement": "map(children, function[(thisArg)])",
			"description": "Invokes a function on every immediate child contained within <code>children</code> with this set to <code>thisArg</code>. If <code>children</code> is a keyed fragment or array it will be traversed: the function will never be passed the container objects. If children is <code>null</code> or <code>undefined</code>, returns <code>null</code> or <code>undefined</code> rather than an array.",
			"status": "optional",
			"returns": "[elements]",
			"returns_description": "Array of elements",
			"parameters": [
				{
					"name": "children",
					"description": "Children which should be invoked with the given function"
				},
				{
					"name": "function",
					"description": "Function which should be invoked for the given elements"
				}
			]
		},
		{
			"name": "forEach",
			"statement": "forEach(children, function[(thisArg)])",
			"description": "Like <code>map()</code>, but not returns an array.",
			"status": "optional",
			"parameters": [
				{
					"name": "children",
					"description": "Children which should be invoked with the given function"
				},
				{
					"name": "function",
					"description": "Function which should be invoked for the given elements"
				}
			]
		},
		{
			"name": "count",
			"statement": "count(children)",
			"description": "Returns the total number of components in <code>children</code>, equal to the number of times that a callback passed to <code>map</code> or <code>forEach</code> would be invoked.",
			"status": "optional",
			"returns": "number",
			"returns_description": "Number of counted elements",
			"parameters": [
				{
					"name": "children",
					"description": "Array of children"
				}
			]
		},
		{
			"name": "only",
			"statement": "only(children)",
			"description": "Verifies that <code>children</code> has only one child (a React element) and returns it. Otherwise this method throws an error.",
			"status": "optional",
			"parameters": [
				{
					"name": "children",
					"description": "Child elements"
				}
			],
			"note": "<code>React.Children.only()</code> does not accept the return value of <code>React.Children.map()</code> because it is an array rather than a React element."
		},
		{
			"name": "toArray",
			"statement": "toArray(children)",
			"description": "Returns the <code>children</code> opaque data structure as a flat array with keys assigned to each child. Useful if you want to manipulate collections of children in your render methods, especially if you want to reorder or slice <code>this.props.children</code> before passing it down.",
			"status": "optional",
			"parameters": [
				{
					"name": "children",
					"description": "Child elements"
				}
			],
			"note": "<code>React.Children.toArray()</code> changes keys to preserve the semantics of nested arrays when flattening lists of children. That is, <code>toArray</code> prefixes each key in the returned array so that each elementâ€™s key is scoped to the input array containing it."
		}
	]
}
